version: '3.9'

services:
  service1:
    build:
      context: service1/
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://service1-db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - service1-db
    env_file:
      - .env

  service1-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d:ro
      - service1-mysql-data:/var/lib/mysql
    command: --pid-file=/var/run/mysqld/mysqld.pid
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u${DB_USER} -p${DB_PASSWORD} || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s

  service2:
    build:
      context: service2/
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://service2-db:3306/otherdatabase
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - service2-db
    env_file:
      - .env

  service2-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: otherdatabase
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d:ro
      - service2-mysql-data:/var/lib/mysql
    command: --pid-file=/var/run/mysqld/mysqld.pid
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u${DB_USER} -p${DB_PASSWORD} || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  service1-mysql-data:
  service2-mysql-data:
